# Generated by Django 5.2.6 on 2025-11-27 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_appuser_profile_image_jddraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jd_id', models.CharField(max_length=255)),
                ('jd_title', models.CharField(max_length=255)),
                ('jd_department', models.CharField(max_length=100)),
                ('resume_id', models.CharField(max_length=255)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('match_score', models.CharField(blank=True, max_length=10, null=True)),
                ('matched_skills', models.JSONField(default=list)),
                ('experience_years', models.IntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('resume_s3_url', models.URLField(blank=True, null=True)),
                ('resume_file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_matches', to='resume.appuser')),
            ],
            options={
                'db_table': 'confirmed_matches',
                'unique_together': {('jd_id', 'resume_id')},
            },
        ),
    ]
