# Generated by Django 5.2.6 on 2025-11-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_confirmedmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedmatch',
            name='hiring_manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='confirmedmatch',
            name='hiring_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
