# Generated by Django 5.2.6 on 2025-11-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_confirmedmatch_hiring_manager_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedmatch',
            name='hiring_manager_email',
        ),
        migrations.RemoveField(
            model_name='confirmedmatch',
            name='hiring_manager_name',
        ),
    ]
