# Generated by Django 5.2.6 on 2025-12-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_confirmedmatch_hiring_manager_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedmatch',
            name='hiring_stage',
            field=models.CharField(default='Applied', max_length=100),
        ),
    ]
