# Generated by Django 5.2.6 on 2025-12-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_confirmedmatch_hiring_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedmatch',
            name='candidate_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
